
server:
  port: 9090

#?serverTimezone=GMT%2B8

spring:
  datasource:
      url: jdbc:postgresql://127.0.0.1:5432/shirodemo
      username: postgres
      password: 123456
      driverClassName: org.postgresql.Driver
      useSSL: false

  jpa:
      hibernate:
        ddl-auto: update
      properties:
        temp:
          use_jdbc_metadata_defaults: false






