
server:
  port: 9090

spring:
  datasource:
      url: jdbc:mysql://192.168.209.36:3306/ry?serverTimezone=GMT%2B8
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      useSSL: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



